export const menProducts = [
    {
      id: 1,
      title: "Classic Black T-Shirt",
      description: "Premium cotton t-shirt with a comfortable regular fit.",
      price: 1499,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCul5ovH-a_vvCfIS4tRcQeK_eC38twOz2utC9J_KrLg&s=10",
    },
    {
      id: 2,
      title: "Blue Denim Jeans",
      description: "Slim-fit stretch denim jeans for everyday wear.",
      price: 2999,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRwlbfdg1rSoidyCWCZMfmXzCQeZcYgmDjtTD_GC-23Q&s=10",
    },
    {
      id: 3,
      title: "White Sneakers",
      description: "Lightweight sneakers with soft cushioned sole.",
      price: 4599,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTyUQlh8kECIZn1Pkf0UfbJrFQGUMlns6Khi19Pb5XUQ&s=10",
    },
    {
      id: 4,
      title: "Formal White Shirt",
      description: "Long sleeve formal shirt made with premium fabric.",
      price: 2499,
      image: "https://najibmaya.pk/cdn/shop/products/ts304-700x700.jpg?v=1664229622",
    },
    {
      id: 5,
      title: "Leather Jacket",
      description: "Stylish faux leather jacket for winter season.",
      price: 7499,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKqmILxnD6mz0nHkhf66HNrCcskDLBTniTyS8rT82Xag&s=10",
    },
    {
      id: 6,
      title: "Grey Hoodie",
      description: "Warm fleece hoodie with adjustable drawstring.",
      price: 3299,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTY-Tu1hPYI6fKkRrHytrQhOEyGeN2NqN5WLX0J-ASUhA&s=10",
    },
    {
      id: 7,
      title: "Sports Watch",
      description: "Water-resistant digital sports watch.",
      price: 5499,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1i68ucKqazg8qZycG4T1AEvu50I5ofbxd6YJC5RXlkA&s=10",
    },
    {
      id: 8,
      title: "Running Shoes",
      description: "Breathable running shoes with rubber outsole.",
      price: 4899,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRltf0bdckekReZhDf_lM0ur2PvKGJn0fNtMlxYI6OorA&s=10",
    },
    {
      id: 9,
      title: "Polo T-Shirt",
      description: "Soft cotton polo t-shirt with modern fit.",
      price: 1999,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPA3PMJkodiZ2c9HRSNlwp8w-MioYz2YjMDow_YjOS-g&s=10,"
    },
    {
      id: 10,
      title: "Cargo Pants",
      description: "Comfortable cargo pants with multiple pockets.",
      price: 3599,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROyzzuFk-0CiiBtsI8w2pW7BRiWT-k4KFnw4htKrAxZg&s=10",
    },
  ];

export const womenProducts = [
    {
      id: 1,
      title: "Floral Summer Dress",
      description: "Elegant floral dress made from soft breathable fabric.",
      price: 3499,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZxjtkHltDRFO8eN7DTeMpOT2p4XrOT6iuJbbsGxXLJg&s=10",
    },
    {
      id: 2,
      title: "Pink Handbag",
      description: "Stylish handbag with spacious compartments.",
      price: 2799,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROWQKtnyzGpmGUBg7D0UBQAyvt6BdCgRDOA5vFt242TA&s=10",
    },
    {
      id: 3,
      title: "White Sneakers",
      description: "Comfortable casual sneakers for everyday wear.",
      price: 4299,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMnXL3T9b8F3HFv-peaXLWWGVGyihH1xISRJmOVrFCeA&s=10",
    },
    {
      id: 4,
      title: "Blue Denim Jacket",
      description: "Classic denim jacket with a modern fit.",
      price: 4999,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4a2cwxBfBD0cGGhXOVNEUmUn6bl8r3Kp2MZAoGCGaJg&s=10",
    },
    {
      id: 5,
      title: "Silk Scarf",
      description: "Premium silk scarf with elegant printed design.",
      price: 1499,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk9AKPUQ4qBra0sN_0kZfu68edbItEBQSVvmSIXQQY5w&s=10",
    },
    {
      id: 6,
      title: "High Heel Sandals",
      description: "Elegant heels perfect for parties and events.",
      price: 3899,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-yPmm_G8MfBuWdFf_fxZEHuQ7UHtzbE0KeUNBA5tQbw&s=10",
    },
    {
      id: 7,
      title: "Yoga Leggings",
      description: "Stretchable high-waist leggings for workouts.",
      price: 1999,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxvTpU918j6PLLcBhMdV-M_OPAftwqsd9IwYBDzKVKTQ&s=10",
    },
    {
      id: 8,
      title: "Casual Blouse",
      description: "Lightweight blouse with a relaxed fit.",
      price: 2299,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0pTHUz6VqMjLoaUk2t1hdCSEUTP1wsZoaxowgNNWfSQ&s=10",
    },
    {
      id: 9,
      title: "Long Winter Coat",
      description: "Warm long coat with premium finishing.",
      price: 6999,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnrQOkpky_HOStbEYh9uTWyBuiqzFSbK-xvlNQ1S3Fhg&s=10",
    },
    {
      id: 10,
      title: "Leather Wallet",
      description: "Compact leather wallet with multiple card slots.",
      price: 1699,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-S8_G7a-Nis9kMZDL40KY-WDmhVuAnzFh8JRjQHKtXQ&s=10",
    },
  ];

export const kidsProducts = [
    {
      id: 1,
      title: "Cartoon Hoodie",
      description: "Soft fleece hoodie with colorful cartoon print.",
      price: 1799,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT17rZAcIGfQopB2MVwNEeWb0agRkVRjDaelEIMhRmmTQ&s=10",
    },
    {
      id: 2,
      title: "Kids Running Shoes",
      description: "Comfortable lightweight shoes for active kids.",
      price: 2499,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPHkWzgqI28osEQSGXO0jeT1Nywb_rX67iy3QcYk2KQQ&s=10",
    },
    {
      id: 3,
      title: "Printed T-Shirt",
      description: "100% cotton t-shirt with fun superhero graphics.",
      price: 899,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTv0avOPnz5y1JXqvtQXMUIDlAvZhtpI4GcLgMi501ZYQ&s",
    },
    {
      id: 4,
      title: "Denim Shorts",
      description: "Comfortable denim shorts for daily wear.",
      price: 1399,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAMHbc69pxYh2dvfJvgZ8TFy1WBxY6LxQbnCPB5TYuBg&s=10",
    },
    {
      id: 5,
      title: "School Backpack",
      description: "Spacious backpack with adjustable shoulder straps.",
      price: 1899,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ02b5TiWl9s-cfZ6PwfDKu35Lje9lYcG4f40j3XN7Tw&s=10",
    },
    {
      id: 6,
      title: "Building Blocks Set",
      description: "Creative educational building blocks for kids.",
      price: 1599,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaRcxiWkGQrWG-JIJtJhUuOq14_rMXFWzlXrAMYU44LA&s=10",
    },
    {
      id: 7,
      title: "Remote Control Car",
      description: "Rechargeable RC racing car with remote control.",
      price: 2899,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7ylUXs2XsYaUj2212dbKmz4NJZ-MBpZLtXfmMr9rtxQ&s=10",
    },
    {
      id: 8,
      title: "Story Book Collection",
      description: "Illustrated bedtime stories for young readers.",
      price: 799,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTff_qcYmFmzJGur97fxgElkFvCKm8bQvvwVp5AG3hPfg&s=10",
    },
    {
      id: 9,
      title: "Kids Sandals",
      description: "Comfortable non-slip sandals for summer.",
      price: 1299,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrgVar15kq1lHVhuOtFDBc2u-4pLUb7klPQlhMT4LUog&s=10",
    },
    {
      id: 10,
      title: "Baseball Cap",
      description: "Adjustable cotton cap with embroidered design.",
      price: 699,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfIJV4Y3crSX334jRnNpMf3lhzqmtvSnpnSPolIHfuVQ&s=10",
    },
  ];